### ISSUE TITLE
error

### ISSUE THREAD

**Issue by mohammed-sec2010** [pankajjha/pj-scraper#1]
ali-VirtualBox node # node minimal.js  
[i] [se-scraper] started at [Wed, 19 Aug 2020 07:58:20 GMT] and scrapes google with 1 keywords on 1 pages each.
(node:9393) UnhandledPromiseRejectionWarning: Error: Unable to launch browser for worker, error message: Browser is not downloaded. Run "npm install" or "yarn install"
    at Cluster.<anonymous> (/opt/node/node_modules/se-scraper/src/puppeteer-cluster/dist/Cluster.js:143:23)
    at Generator.throw (<anonymous>)
    at rejected (/opt/node/node_modules/se-scraper/src/puppeteer-cluster/dist/Cluster.js:5:65)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:9393) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:9393) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by pankajjha** [comment]
Seems like the chromium isn't installed in the system, if you are using ubuntu or centos make sure you install all the dependencies required to run the [puppeteer](https://github.com/puppeteer/puppeteer) 

Chrome and puppeteer [need some additional libraries to run on ubuntu](https://techoverflow.net/2018/06/05/how-to-fix-puppetteer-error-while-loading-shared-libraries-libx11-xcb-so-1-cannot-open-shared-object-file-no-such-file-or-directory/).

## install all that is needed by chromium browser. Maybe not everything needed
`
sudo apt-get install gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget;`
